[package]
name = "problem_1"
version = "0.1.0"
authors = ["Kim Nilsson <nilekurt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc2020-common = { path = "../aoc2020-common" }
